version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: app-dev.containerfile
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5173:5173"
      - "24678:24678"